# Generated by Django 4.1.3 on 2022-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
